---
# Doc: https://github.com/Dallinger/Griduniverse/blob/one-hour-one-life/dlgr/griduniverse/game_config.yml
player_config:
  probability_distribution: "center_bias"
  available_colors:
    BLUE: [0.50, 0.86, 1.00]
    YELLOW: [1.00, 0.86, 0.50]
    ORANGE: [0.91, 0.50, 0.02]
    RED: [0.64, 0.11, 0.31]
    PURPLE: [0.85, 0.60, 0.85]
    TEAL: [0.77, 0.96, 0.90]


item_defaults:
  item_id: default
  name: Default Item
  item_count: 0
  n_uses: 1
  calories: 0
  crossable: true
  interactive: true
  portable: true
  maturation_speed: 0.0
  maturation_threshold: 0.0
  plantable: false
  planting_cost: 1
  probability_distribution: "center_bias"
  public_good_multiplier: 0.0
  respawn: true
  limit_quantity: false
  seasonal_growth_rate: 1.0
  spawn_rate: 1
  sprite: "color:#8a9b0f,#7a6b54" # ("image:sprites/strawberry.png"), "emoji:ğŸ“", "color:#8a9b0f"

transition_defaults:
  visible: seen
  actor_end: null
  actor_start: null
  target_end: null
  target_start: null
  last_use: false
  modify_uses: [0, 0]

items:
  - sprite: "emoji:ğŸˆ"
    name: melon
    item_id: melon
    calories: 1
    item_count: 10
  - sprite: "emoji:ğŸ"
    name: melon_1
    item_id: melon_1
    calories: 1
    item_count: 0
  - sprite: "emoji:ğŸ‹"
    name: melon_2
    item_id: melon_2
    calories: 1
    item_count: 0
  - sprite: "emoji:ğŸŠ"
    name: melon_3
    item_id: melon_3
    calories: 10
    item_count: 0

  - sprite: "emoji:ğŸ«"
    name: blueberry
    item_id: blueberry
    calories: 1
    item_count: 4
  - sprite: "emoji:ğŸ‡"
    name: grapes
    item_id: grapes
    calories: 10
    item_count: 0


  - sprite: "emoji:ğŸª¨"
    name: rock
    item_id: rock
    item_count: 2
  - sprite: "emoji:ğŸ’§"
    name: water
    item_id: water
    item_count: 2
  - sprite: "emoji:ğŸŒ¿	"
    name: herb
    item_id: herb
    item_count: 2

  - sprite: "emoji:ğŸª„	"
    name: magic
    item_id: magic
    item_count: 1
  - sprite: "emoji:â­ "
    name: magic_1
    item_id: magic_1
    item_count: 0
  - sprite: "emoji:ğŸŒŸ	"
    name: magic_2
    item_id: magic_2
    item_count: 0

  - sprite: "emoji:âœ…"
    name: check
    item_id: check
    item_count: 0


transitions:

  - actor_start: rock
    target_start: melon
    target_end: melon_1
    modify_uses: [1, 0]

  - actor_start: water
    target_start: melon_1
    target_end: melon_2

  - actor_start: herb
    target_start: melon_2
    target_end: melon_3

  - actor_start: magic
    target_start: melon
    target_end: melon_1

  - actor_start: water
    target_start: melon_1
    target_end: melon_2

  - actor_start: rock
    target_start: magic
    target_end: magic_1

  - actor_start: water
    target_start: magic_1
    target_end: magic_2

  - actor_start: herb
    target_start: magic_2
    target_end: check

  - actor_start: check
    actor_end: check
    target_start: melon
    target_end: melon_3
    modify_uses: [1, 0]

  - actor_start: check
    actor_end: check
    target_start: blueberry
    target_end: grapes
    modify_uses: [1, 0]
