---
# Doc: https://github.com/Dallinger/Griduniverse/blob/one-hour-one-life/dlgr/griduniverse/game_config.yml
player_config:
  probability_distribution: "center_bias"
  available_colors:
    BLUE: [0.50, 0.86, 1.00]
    YELLOW: [1.00, 0.86, 0.50]
    ORANGE: [0.91, 0.50, 0.02]
    RED: [0.64, 0.11, 0.31]
    PURPLE: [0.85, 0.60, 0.85]
    TEAL: [0.77, 0.96, 0.90]


item_defaults:
  item_id: default
  name: Default Item
  item_count: 0
  n_uses: 1
  calories: 0
  crossable: true
  interactive: true
  portable: true
  maturation_speed: 0.0
  maturation_threshold: 0.0
  plantable: false
  planting_cost: 1
  probability_distribution: "center_bias"
  public_good_multiplier: 0.0
  respawn: true
  limit_quantity: false
  seasonal_growth_rate: 1.0
  spawn_rate: 0
  sprite: "color:#8a9b0f,#7a6b54" # ("image:sprites/strawberry.png"), "emoji:游꼡", "color:#8a9b0f"

transition_defaults:
  visible: never
  actor_end: null
  actor_start: null
  target_end: null
  target_start: null
  last_use: false
  modify_uses: [0, 0]

items:
  - sprite: "emoji:游댮"
    name: red_1
    item_id: red_1
    calories: 1
    item_count: 4
  - sprite: "emoji:游댴"
    name: red_2
    item_id: red_2
    calories: 1
    item_count: 4
  # - sprite: "emoji:鮫뷢잺"
  #   name: red_3
  #   item_id: red_3
  #   calories: 1
  #   item_count: 4
  - sprite: "emoji:仇벒잺"
    name: red_4
    item_id: red_4
    calories: 1
    item_count: 4
  # - sprite: "emoji:游린"
  #   name: red_5
  #   item_id: red_5
  #   calories: 1
  #   item_count: 4

  # - sprite: "emoji:游릯"
  #   name: brown_1
  #   item_id: brown_1
  #   calories: 10
  #   item_count: 0
  # - sprite: "emoji:游꺓"
  #   name: brown_2
  #   item_id: brown_2
  #   calories: 10
  #   item_count: 0
  # - sprite: "emoji:游닍"
  #   name: brown_3
  #   item_id: brown_3
  #   calories: 10
  #   item_count: 0
  # - sprite: "emoji:游밽"
  #   name: brown_4
  #   item_id: brown_4
  #   calories: 10
  #   item_count: 0
  # - sprite: "emoji:游릶"
  #   name: brown_5
  #   item_id: brown_5
  #   calories: 10
  #   item_count: 0

  # - sprite: "emoji:游"
  #   name: orange_1
  #   item_id: orange_1
  #   calories: 20
  #   item_count: 0
  # - sprite: "emoji:游눤"
  #   name: orange_2
  #   item_id: orange_2
  #   calories: 20
  #   item_count: 0
  # - sprite: "emoji:驕뮖잺"
  #   name: orange_3
  #   item_id: orange_3
  #   calories: 20
  #   item_count: 0
  # - sprite: "emoji:游비"
  #   name: orange_4
  #   item_id: orange_4
  #   calories: 20
  #   item_count: 0
  # - sprite: "emoji:游릲"
  #   name: orange_5
  #   item_id: orange_5
  #   calories: 20
  #   item_count: 0

  # - sprite: "emoji:游릭"
  #   name: green_1
  #   item_id: green_1
  #   calories: 40
  #   item_count: 0
  # - sprite: "emoji:仇勇"
  #   name: green_2
  #   item_id: green_2
  #   calories: 40
  #   item_count: 0
  # - sprite: "emoji:游"
  #   name: green_3
  #   item_id: green_3
  #   calories: 40
  #   item_count: 0
  # - sprite: "emoji:游눜"
  #   name: green_4
  #   item_id: green_4
  #   calories: 40
  #   item_count: 0
  # - sprite: "emoji:游릴"
  #   name: green_5
  #   item_id: green_5
  #   calories: 40
  #   item_count: 0

  # - sprite: "emoji:游댯"
  #   name: blue_1
  #   item_id: blue_1
  #   calories: 80
  #   item_count: 0
  # - sprite: "emoji:游"
  #   name: blue_2
  #   item_id: blue_2
  #   calories: 80
  #   item_count: 0
  # - sprite: "emoji:仇勇"
  #   name: blue_3
  #   item_id: blue_3
  #   calories: 80
  #   item_count: 0
  # - sprite: "emoji:游눛"
  #   name: blue_4
  #   item_id: blue_4
  #   calories: 80
  #   item_count: 0
  # - sprite: "emoji:游릱"
  #   name: blue_5
  #   item_id: blue_5
  #   calories: 80
  #   item_count: 0

  # - sprite: "emoji:丘쀮잺"
  #   name: white_1
  #   item_id: white_1
  #   calories: 160
  #   item_count: 0
  # - sprite: "emoji:"
  #   name: white_2
  #   item_id: white_2
  #   calories: 160
  #   item_count: 0
  # - sprite: "emoji:游쀃"
  #   name: white_3
  #   item_id: white_3
  #   calories: 160
  #   item_count: 0
  # - sprite: "emoji:游밼"
  #   name: white_4
  #   item_id: white_4
  #   calories: 160
  #   item_count: 0
  # - sprite: "emoji:拘럺잺"
  #   name: white_5
  #   item_id: white_5
  #   calories: 160
  #   item_count: 0

transitions:

  - actor_start: red_1
    target_start: red_2
    target_end: red_3

  - actor_start: red_4
    target_start: red_2
    target_end: red_1

  - actor_start: red_2
    target_start: red_1
    actor_end: red_2
    target_end: red_1

  - actor_start: red_1
    target_start: red_4
    actor_end: red_1
    target_end: red_4

  - actor_start: red_4
    target_start: red_1
    actor_end: red_4
    target_end: red_1

  - actor_start: red_2
    target_start: red_4
    actor_end: red_2
    target_end: red_4

  - actor_start: red_1
    target_start: red_1
    actor_end: red_1
    target_end: red_1

  - actor_start: red_2
    target_start: red_2
    actor_end: red_2
    target_end: red_2

  - actor_start: red_4
    target_start: red_4
    actor_end: red_4
    target_end: red_4

  # - actor_start: orange_1
  #   target_start: orange_4
  #   target_end: brown_1

  # - actor_start: orange_4
  #   target_start: orange_1
  #   target_end: brown_4

  # - actor_start: orange_5
  #   target_start: orange_3
  #   target_end: brown_5

  # - actor_start: brown_1
  #   target_start: brown_3
  #   target_end: yellow_1

  # - actor_start: brown_4
  #   target_start: brown_3
  #   target_end: yellow_4

  # - actor_start: brown_5
  #   target_start: brown_2
  #   target_end: yellow_5

  # - actor_start: yellow_1
  #   target_start: yellow_1
  #   target_end: green_1

  # - actor_start: yellow_4
  #   target_start: yellow_2
  #   target_end: green_4

  # - actor_start: yellow_5
  #   target_start: yellow_3
  #   target_end: green_5

  # - actor_start: green_1
  #   target_start: green_5
  #   target_end: blue_1

  # - actor_start: green_4
  #   target_start: green_5
  #   target_end: blue_4

  # - actor_start: green_5
  #   target_start: green_5
  #   target_end: blue_5

  # - actor_start: blue_1
  #   target_start: blue_4
  #   target_end: white_1

  # - actor_start: blue_4
  #   target_start: blue_2
  #   target_end: white_4

  # - actor_start: blue_5
  #   target_start: blue_3
  #   target_end: white_5
